<?php foreach($this->_view->structure as $cluster => $nodes): ?>
	<h1><?php echo $cluster; ?></h1>
	<table class="table table-striped table-condensed">
		<thead>
			<tr>
				<th width="20%">Node</th>
				<th width="20%">IP</th>
				<th width="20%">Port</th>
				<th width="20%">Status</th>
				<th width="20%">Response time</th>        
			</tr>
	  </thead>   
	  <tbody>
		<?php foreach($nodes as $node => $stats): ?>
			<tr>
				<td><?php echo $node; ?></td>
				<td class="center"><?php echo $stats['ip']; ?></td>
				<td class="center"><?php echo $stats['port']; ?></td>
				<td class="center">
					<span class="label <?php if ($stats['state'] == 'UP'): ?>label-success<?php else: ?>label-important<?php endif; ?>">
						<?php if ($stats['state'] == 'UP'): ?>UP<?php else: ?>DOWN<?php endif; ?>
					</span>
				</td>
				<td class="center"><?php echo $stats['responseTime']; ?></td>
			</tr>
		<?php endforeach; ?>
	  </tbody>
	</table>
<?php endforeach; ?>