<style>
.right {
	text-align: right !important;
}
</style>

<?php if ($this->_view->slabs): ?>

	<h1><?php echo $this->_view->clusterName?> : <?php echo $this->_view->nodeName; ?></h1>

	<div class="navbar">
		<div class="navbar-inner">
			<ul class="nav">
				<li class="active"><a href="#">Slabs</a></li>
				<li><a href=".?a=items&amp;c=<?php echo $this->_view->clusterName; ?>&amp;n=<?php echo $this->_view->nodeName; ?>">All items</a></li>
				<li><a href=".?a=search&amp;c=<?php echo $this->_view->clusterName; ?>&amp;n=<?php echo $this->_view->nodeName; ?>">Search</a></li>
			</ul>
		</div>
	</div>

	<table class="table table-striped table-condensed">
		<thead>
			<tr>
				<th width="26%">Slab ID</th>
				<th width="26%">Item count</th>
				<th width="26%">Age</th>
				<th width="11%">Evicted</th>
				<th width="11%"></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach($this->_view->slabs['items'] as $slabId => $slab): ?>
			<tr>
				<td><?php echo $slabId; ?></td>
				<td><?php echo $slab['number']; ?></td>
				<td><?php echo $slab['age']; ?></td>
				<td><?php echo $slab['evicted']; ?></td>
				<td class="right">
					<a class="btn btn-small btn-primary" href=".?a=items&amp;c=<?php echo $this->_view->clusterName; ?>&amp;n=<?php echo $this->_view->nodeName; ?>&amp;s=<?php echo $slabId; ?>"><i class="icon-zoom-in icon-white"></i> Show items</a>
				</td>
			</tr>
		<?php endforeach; ?>
			<tr>
				<td><b>All</b></td>
				<td><b><?php echo $this->_view->slabs['count']; ?></b></td>
				<td>-</td>
				<td>-</td>
				<td></td>
			</tr>
		</tbody>
	</table>

<?php endif; ?>