<?php if ($this->_view->nodeName): ?>
	<h1><?php echo $this->_view->clusterName; ?> : <?php echo $this->_view->nodeName; ?></h1>
	<h2><?php echo $this->_view->key; ?></h2>

	<a class="btn btn-small btn-primary" href="javascript:window.history.back();"><i class="icon-arrow-left icon-white"></i> Take me back</a>

	<div class="clearfix"></div>

	<div style="display:block; margin-top: 20px;">	
		<iframe style="width: 100%; height: 400px;" src=".?a=valueplain&c=<?php echo $this->_view->clusterName; ?>&n=<?php echo $this->_view->nodeName; ?>&k=<?php echo $this->_view->key; ?>"></iframe>
	</div>
<?php endif; ?>
